# Generated by Django 4.2.1 on 2023-07-02 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_recommendedproblems_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Updates',
            new_name='Update',
        ),
    ]
