# Generated by Django 4.2.1 on 2023-07-02 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_updates_update'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecommendedProblems',
            new_name='RecommendedProblem',
        ),
    ]
