# Generated by Django 4.2.1 on 2023-07-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='handle',
            field=models.CharField(default='', max_length=50),
        ),
    ]
