# Generated by Django 4.2.1 on 2023-07-03 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_submission_handle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedproblem',
            name='problem_id',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='problem_id',
        ),
        migrations.AddField(
            model_name='recommendedproblem',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.problem'),
        ),
        migrations.AddField(
            model_name='submission',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.problem'),
        ),
    ]
